#!/usr/bin/env python3
"""Writes the single-header distribution, dist/anbc.h:

    #include "anbc.h"                    -- the public API, anywhere
    #define ANBC_IMPLEMENTATION          -- in exactly one translation unit
    #include "anbc.h"

That one file is compiled as Objective-C++ (.mm) on macOS (the Metal
backend) and as C on Windows / Linux (the Vulkan backend). Everything the
backends load at runtime -- Metal sources, the BC7 tensor metallib, SPIR-V --
is the blob generated by pack_blob.py, inlined here.

    amalgamate.py -o dist/anbc.h --blob build/generated/anbc_blob_data.h
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOCAL_INCLUDE_RE = re.compile(r'^#include "anbc[a-z0-9_]*\.h"[^\n]*\n', re.M)
PRAGMA_ONCE_RE = re.compile(r"^#pragma once[^\n]*\n", re.M)

# Implementation sources in dependency order, with the platform guard each
# one is wrapped in (None = always).
IMPLEMENTATION = [
    ("src/anbc_internal.h", None),
    ("src/anbc_blob.h", None),
    ("src/anbc_model.c", None),
    ("src/anbc.c", None),
    ("src/anbc_blob.c", None),
    ("src/anbc_vulkan.h", None),
    ("src/backend_vulkan.c", None),
    ("src/backend_metal.mm", "defined(__APPLE__) && defined(__OBJC__)"),
]


def section(path: Path, text: str) -> str:
    text = LOCAL_INCLUDE_RE.sub("", text)
    text = PRAGMA_ONCE_RE.sub("", text)
    return f"/* ---- {path.as_posix()} {'-' * max(1, 70 - len(path.as_posix()))} */\n{text.rstrip()}\n\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("-o", "--output", required=True, type=Path)
    parser.add_argument("--blob", required=True, type=Path, help="anbc_blob_data.h from pack_blob.py")
    args = parser.parse_args()

    out = "/* anbc -- single-header build, generated by tools/amalgamate.py. Do not edit.\n"
    out += " * Define ANBC_IMPLEMENTATION in one translation unit before including this\n"
    out += " * file: an Objective-C++ (.mm) file on macOS (Metal 4 backend), a C file on\n"
    out += " * Windows / Linux (Vulkan backend). See notes.txt section 4. */\n\n"
    out += section(Path("include/anbc.h"), (ROOT / "include/anbc.h").read_text())

    out += "#ifdef ANBC_IMPLEMENTATION\n#ifndef ANBC_IMPLEMENTATION_DONE\n#define ANBC_IMPLEMENTATION_DONE\n\n"
    out += "/* The Metal backend needs this translation unit to be Objective-C++ (.mm). */\n"
    out += "#if defined(__APPLE__) && defined(__OBJC__)\n#define ANBC_HAVE_METAL 1\n#endif\n\n"
    for rel, guard in IMPLEMENTATION:
        path = Path(rel)
        if rel == "src/anbc_blob.c":
            text = section(path, args.blob.read_text())
        else:
            text = section(path, (ROOT / rel).read_text())
        if guard:
            text = f"#if {guard}\n{text}#endif /* {guard} */\n\n"
        out += text
    out += "#endif /* ANBC_IMPLEMENTATION_DONE */\n#endif /* ANBC_IMPLEMENTATION */\n"

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(out)
    print(f"wrote {args.output} ({args.output.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
