#!/usr/bin/env python3
"""Packs the shader artefacts the library loads at runtime (Metal sources,
metallibs, SPIR-V) into one blob and writes it as a C header.

    pack_blob.py -o generated/anbc_blob_data.h NAME=FILE[+FILE...] ...

An entry's value is one file, or several joined with '+': those are
concatenated in order (the runtime-compiled Metal libraries are one library
per format, made of the shared .metal files followed by the kernel file).
Their `#include "anbc_*.metal"` lines are dropped: the offline compile needs
them, the concatenation already has every file in dependency order and each
carries an include guard.

Blob layout (little-endian, see anbc_blob.h):
    u32 magic 'ANBB'   u32 count   u32 tocOffset   u32 dataOffset
    count x { char name[40]; u32 offset; u32 size; }   (offset from blob start)
    payloads, each 4-byte aligned; text payloads get a trailing NUL that is
    not counted in `size`, so Metal sources are usable as C strings.
The output defines `anbcBlobData` as a uint32_t array (so SPIR-V is aligned)
with external linkage; anbc_blob.c is the one translation unit including it.
"""

from __future__ import annotations

import argparse
import re
import struct
from pathlib import Path

NAME_BYTES = 40
INCLUDE_RE = re.compile(rb'#include "anbc_[a-z0-9_]+\.metal"[^\n]*\n')
TEXT_SUFFIXES = {".metal", ".glsl", ".comp"}


def align4(n: int) -> int:
    return (n + 3) & ~3


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("-o", "--output", required=True, type=Path)
    parser.add_argument("entries", nargs="+", help="NAME=FILE[+FILE...]")
    args = parser.parse_args()

    payloads: list[tuple[str, bytes, bool]] = []
    for entry in args.entries:
        name, _, files = entry.partition("=")
        if not name or not files:
            raise SystemExit(f"bad entry {entry!r}, want NAME=FILE[+FILE...]")
        if len(name.encode()) >= NAME_BYTES:
            raise SystemExit(f"entry name {name!r} longer than {NAME_BYTES - 1} bytes")
        parts = [Path(f) for f in files.split("+")]
        text = all(p.suffix in TEXT_SUFFIXES for p in parts)
        data = b""
        for p in parts:
            part = p.read_bytes()
            if text:
                part = INCLUDE_RE.sub(b"", part) + b"\n"
            data += part
        if text:
            data += b"\0"
        payloads.append((name, data, text))

    toc_offset = 16
    data_offset = align4(toc_offset + len(payloads) * (NAME_BYTES + 8))
    toc = b""
    body = b""
    for name, data, text in payloads:
        offset = data_offset + len(body)
        size = len(data) - 1 if text else len(data)  # the NUL is not part of a text payload
        toc += name.encode().ljust(NAME_BYTES, b"\0") + struct.pack("<II", offset, size)
        body += data + b"\0" * (align4(len(data)) - len(data))
    blob = struct.pack("<4sIII", b"ANBB", len(payloads), toc_offset, data_offset) + toc
    blob += b"\0" * (data_offset - len(blob)) + body
    assert len(blob) % 4 == 0

    words = struct.unpack(f"<{len(blob) // 4}I", blob)
    lines = [",".join(f"0x{w:08x}" for w in words[i : i + 8]) + "," for i in range(0, len(words), 8)]
    names = ", ".join(name for name, _, _ in payloads)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        f"/* Generated by pack_blob.py -- do not edit. Entries: {names} */\n"
        "#include <stdint.h>\n"
        f"const uint32_t anbcBlobData[{len(words)}] = {{\n" + "\n".join(lines) + "\n};\n"
    )


if __name__ == "__main__":
    main()
